version: "3.8"
services:
  dashboard-front-end:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./dockersecretproduction.env
    ports:
      - "5910:5910"
    restart: always
