import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import Providers from "./providers";
import { getAuthSession } from "@/lib/authSession";
import { createGuestUser, getAuthGuestSession } from "@/lib/authGuestSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getAuthSession();
    const guestSession = await getAuthGuestSession();
    if (!session.access && !guestSession?.user?.id) {
        await createGuestUser();
    }

    return (
        <html lang="en">
            <body className={`${inter.className} max-w-vw`}>
                <Providers>{children}</Providers>
                <div id="modal-wrapper" />
            </body>
        </html>
    );
}
